article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    # path('',views.article, name='article'),
    # path('article_list/',views.article_list, name='article_list'), 
    path('article_serach/',views.article_serach, name='article_serach'),
    path('<int:id>/',views.article_detail, name='article_detail'),
]

cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('',views.cms, name='cms'),
    path('recommend/',views.recommend, name='recommend'),
    path('recommend_post/',views.recommend_post, name='recommend_post'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('',views.community, name='community'),
    path('topic/<int:id>/',views.topic_detail, name='topic_detail'),
    path('topic_create',views.topic_create, name='topic_create'),
    path('topic_comment',views.topic_comment, name='topic_comment'),
    path('topic_comment_like',views.topic_comment_like, name='topic_comment_like'),
    path('category=<str:category>',views.topic_categry, name='topic_categry'),
    path('topic_search',views.topic_search, name='topic_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from mysite import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('public.urls')),
    path('article/',include('article.urls', namespace="article")),
    path('user/',include('userprofile.urls', namespace="userprofile")),
    path('cms/',include('cms.urls', namespace="cms")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('personal/',include('personal_center.urls')),
    path('community/',include('community.urls')),
    path('functions/',include('functions.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

personal_center/urls.py
from django.urls import path
from . import views

app_name = 'personal_center'

urlpatterns = [
    path('',views.personal_center_home, name='personal_center_home'),
    path('article_release/',views.article_release, name='article_release'),
    path('article_create/',views.article_create, name='article_create'),
    path('tag_release/',views.tag_release, name='tag_release'),
    path('anthology_release/',views.anthology_release, name='anthology_release'),
    path('anthology_create/',views.anthology_create, name='anthology_create'),
    path('anthology/<int:id>/',views.anthology_article, name='anthology_article'),
    path('p_<int:id>',views.public_author_message, name='public_author_message'),
    path('author_follow',views.author_follow, name='author_follow'),
    path('message_center',views.message_center, name='message_center'),
    path('information',views.information, name='information'),
    path('information_change/',views.information_change, name='information_change'),
    path('portrait_change/',views.portrait_change, name='portrait_change'),
    path('topics/',views.topic_show, name='topic_show'),
    path('anthology_delete/',views.anthology_delete, name='anthology_delete'),
    path('anthology_change/',views.anthology_change, name='anthology_change'),
    path('anthology_revise/',views.anthology_change_handle, name='anthology_change_handle'),
    path('article_delete/',views.article_delete, name='article_delete'),
    path('article_change/',views.article_change, name='article_change'),
    path('article_revise/',views.article_change_handle, name='article_change_handle'),
    path('follows/',views.follow_show, name='follow_show'),
    path('fans/',views.fans_show, name='fans_show'),
    path('p_<int:id>/anthologys',views.public_author_anthologys, name='public_author_anthologys'),
    path('anthology_<int:id>/articles',views.public_author_articles, name='public_author_articles'),
    path('p_<int:id>/follows',views.public_author_follows, name='public_author_follows'),
    path('p_<int:id>/fans',views.public_author_fans, name='public_author_fans'),
]

userprofile/urls.py
from django.urls import path
from . import views
import re

app_name = 'userprofile'

urlpatterns = [
    path('login/post/',views.user_login, name='user_login'),
    path('logout/',views.user_logout, name='user_logout'),
    path('register/post/',views.user_register, name='user_register'),
    path('captcha/',views.img_captcha,name='img_captcha'),
    path('login/',views.login_show, name='login_show'),
    path('register/',views.register_show, name='register_show'),
    path('reset_user/',views.reset_show, name='reset_show'),
    path('reset_code/',views.reset_code, name='reset_code'),
    path('reset_confirm/',views.reset_confirm, name='reset_confirm'),
    path('reset_pwd/',views.reset_pwd, name='reset_pwd'),
    path('pwd_show/',views.pwd_show, name='pwd_show'),
    # path('remind/',views.remind_show, name='remind_show'),
    path("reset_password/<slug:code>",views.remind_show, name='remind_show'),     
]


# Django默认支持以下5个转化器：

# str,匹配除了路径分隔符（/）之外的非空字符串，这是默认的形式
# int,匹配正整数，包含0。
# slug,匹配字母、数字以及横杠、下划线组成的字符串。
# uuid,匹配格式化的uuid，如 075194d3-6885-417e-a8a8-6c931e272f00。
# path,匹配任何非空字符串，包含了路径分隔符

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import exceptions
from ckeditor_uploader.fields import RichTextUploadingField

# 关于是用User做关联还是Profile的思考：
# 1、关联的目的是为了找到用户信息，尤其是用户名，这一点上两个都能做到
# 2、首先用户登录肯定是用User中的账号密码登录，后端显示文章肯定也是根据传递的用户模型去搜索进行返回
# 3、无疑肯定是直接用User最直接，然后通过user.username找到用户名然后进行标注就可以了

# 模型之间的关系设定：
# 1、文章肯定是主题，所有功能都通过文章来设计
# 2、但是每篇文章必须要有一个单独的文章集合属性，这个属性可定设定多个，相当于文章集合与文章是一对多的关系
class Anthology(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    anthology_title = models.CharField(max_length=20,default='默认文选')
    anthology_cover = models.ImageField(upload_to='covers/',default='covers/anthology.jpg')
    anthology_describe = models.CharField(max_length=200,default='暂无描述')
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.anthology_title


# class Tag(models.Model):
#     tag = models.CharField(max_length=20)

    # class Meta:
    #     db_table = 'tag'



# class Category(models.Model):
#     category = models.CharField(max_length=20)

    
    # class Meta:
    #     db_table = 'category'


# 注意
# 1、其实在这个文章模型中最特殊的是文章集合，当用户点击文章集合的时候必须要按照一定的顺序显示
# 2、那么问题是，如果我的文章刚开始是随意写的，最后想要按照一定的顺序进行排序，怎么办，
#    这就需要搭配一个序列号字段，序列号字段是需要用户自主填写的
#  
class Article(models.Model):
    # 文章标题，必填
    article_title = models.CharField(max_length=50)
    # 引入文集的外键，一对多，这个字段可以由
    anthology = models.ForeignKey(Anthology,on_delete=models.CASCADE,null=True)
    # 自主标签
    # tags = models.ManyToManyField(Tag,related_name='articles')
    # 系统分类
    category = models.CharField(max_length=20,default='数据分析')
    # categorys = models.ManyToManyField(Category,related_name='articles')
    # 文章序列号，用来表明这是“文集”的第几个，默认为第一个
    serial = models.IntegerField(default='1')
    # 作者，这个作者是真是有账号的作者
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    # 作者，这个作者是假作者，用来备用，没有对应的用户，只是单纯的字符串
    author_copy = models.CharField(max_length=20,blank=True)
    # 文章摘要，用来简明扼要的阐述主题，可以为空
    summary = models.CharField(max_length=200,blank=True)
    # 文章内容，不能为空
    content = RichTextUploadingField()
    # 文章封面，不能为空，用来做推荐时候的封面
    article_cover = models.ImageField(upload_to='covers/')
    
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    # 文章排序功能，可排序的字段为：最近投稿、阅读次数最多、阅读人数最多、点赞最多、收藏最多、评论最多
    read_num = models.IntegerField(default='0')
    reader_num = models.IntegerField(default='0')
    like_num = models.IntegerField(default='0')
    collect_num = models.IntegerField(default='0')
    comment_num = models.IntegerField(default='0')
    # 公开状态，默认公开，关闭则只对自己可见
    # is_open = models.BooleanField(default=True,verbose_name='公开状态')
    # 激活状态，默认激活，不激活则显示被删除，这个是逻辑删除字段
    is_active = models.BooleanField(default=True)
    #是否需要付费，默认不需要
    is_pay = models.BooleanField(default=False)
    # 需要支付多少钱
    need_pay = models.IntegerField(default='0')

        

    def __str__(self):
        return "<Article: %s>" % self.article_title
    
    class Meta:
        ordering = ['-created_time',]

    # class Meta:
    #     db_table = 'article'
    

class ReaderNum(models.Model):
    reader = models.ForeignKey(User,on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # 第一次阅读的时间
    once_read_time = models.DateTimeField(auto_now_add=True)
    # 重新阅读的时间
    more_read_time = models.DateTimeField(auto_now=True)

cms/models.py
from django.db import models

# 各个页面的推荐
# 目前就只有文章、文选、作者这三个主体
class Recommend(models.Model):
    # 推荐类型，每个对应的数字代表着不同的推荐位置
    recommend_type =  models.IntegerField()
    # 推荐主体的id,用来寻找推荐的主体
    recommend_id = models.CharField(max_length=50, verbose_name="推荐id")
    # 推荐语，如果不写默认为推荐主体的标题
    recommend_text = models.CharField(max_length=200, verbose_name="推荐语")
    recommend_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-recommend_time']

cms/forms.py
from django import forms
# from ckeditor_uploader.widgets import CKEditorUploadingWidget
# from django.contrib.auth import authenticate
# from django.core.cache import cache

class RecommendForm(forms.Form):
    recommend_type = forms.IntegerField()
    recommend_id = forms.CharField()
    recommend_text = forms.CharField()

article/views.py
from django.shortcuts import get_object_or_404,render,redirect,render_to_response
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.db.models import Q
from .models import Article,ReaderNum
from functions.models import ArticleComment

# def home(request):
# 	return render(request, 'home.html')

def article_detail(request,id):
	# 获取文章
	article = get_object_or_404(Article,id=id)
	# 每次打开文章的时候，如果用户处于登录状态，那么就获取或者创建一条阅读记录
	if request.user.is_authenticated:
		reader = request.user
		reader_num, created = ReaderNum.objects.get_or_create(article=article, reader=reader)
		# 这里有两种技术方法，一个是判断是否是新建的，但是这种很容易在后台出错的时候遗漏，这里采用第二种方法，直接对该文章的阅读记录进行一个计数，然后赋值
		reader_num = ReaderNum.objects.filter(article=article).count()
		# 对该文章的阅读记录进行计数，如果数据库中的阅读人数少于计数量，则更新
		if article.reader_num != reader_num:
			article.reader_num = reader_num
		
	# 无论用户是否登录，只要改文章打开，那么阅读数+1
	article.read_num += 1
	article.save(update_fields=['read_num','reader_num'])
	# 该作者最新发布的5篇文章
	latest_articles = Article.objects.filter(author=article.author)[0:5]
	# 获取文章的评论
	article_comments = ArticleComment.objects.filter(article=article, parent=None).order_by('-comment_time')
	# 对搜索结果分页
	paginator = Paginator(article_comments,20)
	page_num = request.GET.get('page',1)
	page_of_comments = paginator.get_page(page_num)
	#总页数
	num_pages = paginator.num_pages

	# 设定当前页左右显示页数
	around_count = 2
	# 获取当前页码、左侧页码、右侧页码
	current_page = page_of_comments.number

	left_has_more = False
	right_has_more = False
	if current_page <= around_count+2:
		left_pages = range(1,current_page)
	else:
		left_has_more = True
		left_pages = range(current_page-around_count,current_page)
	if current_page >= num_pages-around_count-1:
		right_pages = range(current_page+1,num_pages+1)
	else:
		right_has_more = True
		right_pages = range(current_page+1,current_page+around_count+1)
	hot_articles = Article.objects.all().order_by('-read_num')[0:10]
	context = {}
	# context['search_words'] = search_words
	# context['search_atticles_count'] = search_articles.count()
	context['page_of_comments'] = page_of_comments
	# context['page_range'] = paginator.page_range
	context['left_pages'] = left_pages
	context['current_page'] = current_page
	context['right_pages'] = right_pages
	context['left_has_more'] = left_has_more
	context['right_has_more'] = right_has_more
	context['num_pages'] = num_pages

	
	# context = {}
	context['article'] = article
	# context['article_comments'] = article_comments.order_by('-comment_time')
	context['latest_articles'] = latest_articles
	return render(request,'article.html',context)


def article(request):
	article = get_object_or_404(Article,id=1)
	context = {}
	context['article'] = article
	return render(request,'article.html',context)



def article_serach(request):
	# 获取搜索关键词，并去除首尾空格
	search_words = request.GET.get('search','').strip()
	# 如果有程序直接绕过前端输入了空字符串，那么就直接返回首页
	if len(search_words) == 0:
		return render(request,'home.html')
	else:
		condition = None
		for word in search_words.split(' '):
			if condition is None:
				condition = Q(article_title__icontains=word) | Q(content__icontains=word)
			else:
				condition = condition | Q (article_title__icontains=word) | Q(content__icontains=word)#  ~:非  $:并  |：或        
		search_articles = Article.objects.filter(condition).order_by('-created_time')
		# search_articles = Article.objects.filter(article_title__icontains=search_word)
		# 对搜索结果分页
		paginator = Paginator(search_articles,10)
		page_num = request.GET.get('page',1)
		page_of_articles = paginator.get_page(page_num)
		#总页数
		num_pages = paginator.num_pages

		# 设定当前页左右显示页数
		around_count = 2
		# 获取当前页码、左侧页码、右侧页码
		current_page = page_of_articles.number

		left_has_more = False
		right_has_more = False
		if current_page <= around_count+2:
			left_pages = range(1,current_page)
		else:
			left_has_more = True
			left_pages = range(current_page-around_count,current_page)
		if current_page >= num_pages-around_count-1:
			right_pages = range(current_page+1,num_pages+1)
		else:
			right_has_more = True
			right_pages = range(current_page+1,current_page+around_count+1)
		hot_articles = Article.objects.all().order_by('-read_num')[0:10]
		context = {}
		context['search_words'] = search_words
		context['search_atticles_count'] = search_articles.count()
		context['page_of_articles'] = page_of_articles
		# context['page_range'] = paginator.page_range
		context['left_pages'] = left_pages
		context['current_page'] = current_page
		context['right_pages'] = right_pages
		context['left_has_more'] = left_has_more
		context['right_has_more'] = right_has_more
		context['num_pages'] = num_pages
		context['hot_articles'] = hot_articles
		return render(request,'search.html',context)

templates/community_search.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% load functions_tags %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>社区</title>
    <link rel="shortcut icon" type="image/ico" href="/media/img/favicon.ico">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1469429_oy03njc37a.css">
    <link rel="stylesheet" type="text/css" href="/static/css/head.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="stylesheet" type="text/css" href="/static/css/community.css">
    <link rel="stylesheet" type="text/css" href="/static/css/pop.css">
    <link rel="stylesheet" type="text/css" href="/static/css/foot.css">
</head>
<body>
    <a id="scrollup" href="#top">^</a>
    {% include 'head.html' %}
    <div class="community_top">
        <div class="container">
            <div class="search_word">
                <i class="icon-xiayihuanjie iconfont"></i>
                搜索：<span>{{ search_words }}</span> , 共找到 <span>{{ search_topics_count }}</span> 个话题
            </div>
            <div class="topic_search">
                <form action="{% url 'community:topic_search' %}">
                    <div class="input_box">
                        <input type="text" name="topic_search" id="topic_search"  placeholder="寻找话题" required="required">
                        <button  type="submit" id="topic_search_button"><i class="icon-sousuo iconfont circle_hover"></i></button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
    <div class="community_box">
        <div class="container">
            <div class="community_detail">
                <div class="community_left">
                    <div class="community_class">
                        <div class="community_class_title">帖子分类</div>
                        <div class="community_class_name">
                            <a href="{% url 'community:community' %}"><div class="community_class_list">社区首页</div></a>
                            <a href="{% url 'community:topic_categry' '话题探讨' %}"><div class="community_class_list tantao">话题探讨</div></a>
                            <a href="{% url 'community:topic_categry' '数据思维' %}"><div class="community_class_list siwei">数据思维</div></a>
                            <a href="{% url 'community:topic_categry' '学习交流' %}"><div class="community_class_list jiaoliu">学习交流</div></a>
                            <a href="{% url 'community:topic_categry' '经验之谈' %}"><div class="community_class_list jingyan">经验之谈</div></a>
                            <a href="{% url 'community:topic_categry' '资源共享' %}"><div class="community_class_list gongxiang">资源共享</div></a>
                            <a href="{% url 'community:topic_categry' '技术解惑' %}"><div class="community_class_list jishu">技术解惑</div></a>
                            <a href="{% url 'community:topic_categry' '人工智能' %}"><div class="community_class_list zhineng">人工智能</div></a>
                            <a href="{% url 'community:topic_categry' '茶余饭后' %}"><div class="community_class_list chayu">茶余饭后</div></a>
                        </div>
                    </div>
                </div>

                <div class="community_right">
                    {% if user.is_authenticated %}
                        <a href="javascript:volid(0);"><div class="post_post">发表新帖</div></a>
                    {% else %}
                        <a href="{% url 'userprofile:login_show' %}?next={{ request.path }}"><div class="post_post">发表新帖</div></a>
                    {% endif %}
                    
                    <div class="hot_topic_box">
                        <div class="topic_title">热门话题</div>
                        <div class="topic_hot_show">
                            {% for hot_topic in hot_topics %}
                            <a href="{% url 'community:topic_detail' hot_topic.pk %}">
                                <div class="topic_hot_list">
                                    <i class="icon-hot iconfont"></i>
                                    <p class="hot_topic_title">{{ hot_topic.topic_title }}</p>
                                    
                                </div>
                            </a>
                            {% endfor %}
                           
                            
                            
                        </div>
                    </div>
                    
                </div>

                <div class="community_mid">
                    <div class="community_post">
                        <div class="community_post_title">{{ category }}</div>
                        <div class="community_post_list">
                            {% for topic in page_of_topics %}
                                <a href="{% url 'community:topic_detail' topic.pk %}">
                                    <div class="community_post_box">
                                        <div class="post_name">{{ topic.topic_title }}</div>
                                        <div class="post_detail">
                                            <div class="data_list"><i class="icon-wode iconfont"></i>{{ topic.author.username }}</div>
                                            <div class="data_list"><i class="icon-fenlei iconfont"></i>{{ topic.category }}</div>
                                            <div class="data_list"><i class="icon-daipingjia iconfont"></i>{% get_topiccomments_count topic %}</div>
                                            <div class="data_list"><i class="icon-time1 iconfont"></i>{{ topic.created_time|date:"Y/m/d H:i:s" }}</div>
                                        </div>
                                    </div>
                                </a>
                            {% empty %}

                            {% endfor %}
                            
                           

                        </div>
                        <!-- 分页器 -->
                        <div class="page_cut_box">
                            <!-- 判断是否有上一页 -->
                            {% if page_of_topics.has_previous %}
                                <a href="?page={{ page_of_topics.previous_page_number }}"><div class="page_num_list pre_or_next">上一页</div></a> 
                            {% else %}
                                <a href="javascript:void(0)"><div class="page_num_list pre_or_next">上一页</div></a>
                            {% endif %}
                            
                            {% if left_has_more %}
                                <a href="?page=1"><div class="page_num_list">1</div></a> 
                                <a href="javascript:void(0)"><div class="page_num_list">...</div></a> 
                            {% endif %}

                            {% for left_page in left_pages %}
                                <a href="?page={{ left_page }}"><div class="page_num_list">{{ left_page }}</div></a> 
                                
                            {% endfor %}

                            <a href="javascript:void(0)"><div class="page_num_list active">{{ current_page }}</div></a>

                            {% for right_page in right_pages %}
                                <a href="?page={{ right_page }}"><div class="page_num_list">{{ right_page }}</div></a> 
                                
                            {% endfor %}

                            {% if right_has_more %}
                                <a href="javascript:void(0)"><div class="page_num_list">...</div></a> 
                                <a href="?page={{ num_pages }}"><div class="page_num_list">{{ num_pages }}</div></a> 
                                
                            {% endif %}

                            <!-- 判断是否有下一页 -->
                            {% if page_of_topics.has_next %}
                                <a href="?page={{ page_of_topics.next_page_number }}"><div class="page_num_list pre_or_next">下一页</div></a> 
                            {% else %}
                                <a href="javascript:void(0)"><div class="page_num_list pre_or_next">下一页</div></a>
                            {% endif %}
                            
                        </div>
                        
                        
                        
                    </div>
                    
                </div>
                
            </div>
        </div>
    </div>
    <!-- 评论弹出框 -->
    {% if user.is_authenticated %}
        <div class="pop" style="display: none;">
            <div class="popback">
            </div>
            
            <div class="popbox">
                <div class="close_pop"><i class="icon-guanbi iconfont"></i></div>
                <div class="topic_box">
                    <form id='topic_form'  method="post" action="{% url 'community:topic_create' %}">
                        {% csrf_token %}
                        <div class="topic_category_box">
                            <select name="category" id="topic_category">
                                <option value ="话题探讨">话题探讨</option>
                                <option value ="数据思维">数据思维</option>
                                <option value="经验之谈">经验之谈</option>
                                <option value="资源共享">资源共享</option>
                                <option value="技术解惑">技术解惑</option>
                                <option value="人工智能">人工智能</option>
                                <option value="茶余饭后">茶余饭后</option>
                            </select>
                        </div>
                        <input class="topic_title_input" name="topic_title" placeholder="标题" required="required">
                        <div class="topic_content">
                            {{ topicform.content }}
                        </div>
                        <button type="submit">发表话题</button>
                        
                    </form>   
                </div> 
                
                
                
            </div>
            
        </div>
    {% else %}    
    {% endif %} 

    {% include 'foot.html' %}





    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/pop.js"></script>
    <script src="/static/js/cms.js"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript">


        $(".post_post").click(function(){
            $(".pop").css("display","block");
        });
        
        $(function(){
            $('.head').find('.community').addClass('active');
        })


    </script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>登录</title>
    <link rel="shortcut icon" type="image/ico" href="/media/img/favicon.ico">
    <link rel="stylesheet" type="text/css" href="/static/css/head.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login_logout.css">
    <!-- <link rel="stylesheet" type="text/css" href="/static/css/cms.css"> -->
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1469429_ujc5ugvzv.css">
</head>
<body>
    {% include 'head.html' %}
    <div class="login_box" >
        <div class="container">
            <div class="login_left">
                <div class="biaoyu1">观之数静 知以律动</div>
                <div class="biaoyu2">Observe the data to understand its law</div>
            </div>
            <div class="login_right">
                <div class="welcome">
                    <img src="/media/img/cosdata_red_min.png">
                </div>
                <div class="login_input">
                    <form id='login_form'  method="post" action="{% url 'userprofile:user_login'%}">
                        {% csrf_token %}
                        <div class="log_content">
                            <div class="message"><i class="icon-tongzhi iconfont"></i>{{ message }}</div>
                            <div class="content_list">
                                <input type="text" class="input_set" id="username" name="username" placeholder="账号" required="required">
                            </div>
                            <div class="content_list">
                                <input type="password" class="input_set" id="password" name="password" placeholder="密码" required="required">
                            </div>
                            <div class="content_list">
                                <input type="text" class="input_set" id="img_captcha" name="img_captcha" placeholder="验证码" required="required">
                                <div class="verif_code">
                                    <img class="img_captcha" src="{% url 'userprofile:img_captcha' %}">
                                </div>

                            </div>
                            <div class="content_list">
                                <button type="submit" class="login_immediately">立即登录</button>
                            </div>
                            <div class="content_list2">
                                <input name="remember" id="remember" type="checkbox" value="1">
                                <p>记住我</p>
                            </div>
                            <div class="content_list3">
                                <a href="{% url 'userprofile:register_show' %}">立即注册>></a>
                            </div>
                            <div class="content_list3">
                                <a href="{% url 'userprofile:reset_show' %}">忘记密码</a>
                            </div>

                        </div>
                        
                    </form>  
                </div>

            </div>
        </div>

    </div>

    <script src="/static/js/jquery.min.js"></script>
    <script>
        //点击切换验证码
        $(".img_captcha").click(function(){
            $(this).attr("src","/user/captcha/"+"?random="+Math.random())
        });
    </script>
    
</body>
</html>